apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: pe-backstage-k8sactions-python3
  description: Python app that displays time - named pe-backstage-k8sactions-python3
  annotations:
    github.com/project-slug: gusLopezC/pe-backstage-k8sactions-python3
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
