site_name: 'pe-backstage-k8sactions-python3'
site_description: 'Main documentation for the pe-backstage-k8sactions-python3'
repo_url: https://github.com/gusLopezC/pe-backstage-k8sactions-python3
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'